Opening few files to profile the data and inspect the schemas.

In [1]:
import polars as pl
import os
from dotenv import load_dotenv

In [4]:
import s3fs
load_dotenv()

import s3fs

fs = s3fs.S3FileSystem(
    key=os.getenv("AWS_ACCESS_KEY_ID"),
    secret=os.getenv("AWS_SECRET_ACCESS_KEY")
)

files = fs.glob("s3://techcatalyst-de-2026/raw/**/*.parquet")

for f in files:
    print(f)

print(f"Found {len(files)} parquet files")

techcatalyst-de-2026/raw/green_taxi/green_tripdata_2025-01.parquet
techcatalyst-de-2026/raw/green_taxi/green_tripdata_2025-02.parquet
techcatalyst-de-2026/raw/green_taxi/green_tripdata_2025-03.parquet
techcatalyst-de-2026/raw/green_taxi/green_tripdata_2025-04.parquet
techcatalyst-de-2026/raw/green_taxi/green_tripdata_2025-05.parquet
techcatalyst-de-2026/raw/green_taxi/green_tripdata_2026-01.parquet
techcatalyst-de-2026/raw/green_taxi/green_tripdata_2026-02.parquet
techcatalyst-de-2026/raw/green_taxi/green_tripdata_2026-03.parquet
techcatalyst-de-2026/raw/green_taxi/green_tripdata_2026-04.parquet
techcatalyst-de-2026/raw/green_taxi/green_tripdata_2026-05.parquet
techcatalyst-de-2026/raw/weather/weather_raw.parquet
techcatalyst-de-2026/raw/yellow_taxi/yellow_tripdata_2025-01.parquet
techcatalyst-de-2026/raw/yellow_taxi/yellow_tripdata_2025-02.parquet
techcatalyst-de-2026/raw/yellow_taxi/yellow_tripdata_2025-03.parquet
techcatalyst-de-2026/raw/yellow_taxi/yellow_tripdata_2025-04.parquet
techcatalyst-de-2026/raw/yellow_taxi/yellow_tripdata_2025-05.parquet
techcatalyst-de-2026/raw/yellow_taxi/yellow_tripdata_2026-01.parquet
techcatalyst-de-2026/raw/yellow_taxi/yellow_tripdata_2026-02.parquet
techcatalyst-de-2026/raw/yellow_taxi/yellow_tripdata_2026-03.parquet
techcatalyst-de-2026/raw/yellow_taxi/yellow_tripdata_2026-04.parquet
techcatalyst-de-2026/raw/yellow_taxi/yellow_tripdata_2026-05.parquet
Found 21 parquet files

#### Verify some files

In [ ]:
df = pl.read_parquet("s3://techcatalyst-de-2026/raw/green_taxi/green_tripdata_2025-01.parquet")

df.head()

shape: (5, 21)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ lpep_pick ┆ lpep_drop ┆ store_and ┆ … ┆ payment_t ┆ trip_type ┆ congestio ┆ cbd_conge │
│ ---      ┆ up_dateti ┆ off_datet ┆ _fwd_flag ┆   ┆ ype       ┆ ---       ┆ n_surchar ┆ stion_fee │
│ i32      ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ i64       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ str       ┆   ┆ i64       ┆           ┆ ---       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆           ┆ f64       ┆           │
│          ┆ μs]       ┆ μs]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2025-01-0 ┆ 2025-01-0 ┆ N         ┆ … ┆ 1         ┆ 1         ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:03:01  ┆ 00:17:12  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-01-0 ┆ 2025-01-0 ┆ N         ┆ … ┆ 2         ┆ 1         ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:19:59  ┆ 00:25:52  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-01-0 ┆ 2025-01-0 ┆ N         ┆ … ┆ 2         ┆ 2         ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:05:29  ┆ 00:07:21  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-01-0 ┆ 2025-01-0 ┆ N         ┆ … ┆ 1         ┆ 1         ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:52:24  ┆ 01:07:52  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-01-0 ┆ 2025-01-0 ┆ N         ┆ … ┆ 1         ┆ 1         ┆ 2.75      ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:25:05  ┆ 01:01:10  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [15]:
df.shape

(48326, 21)

In [24]:
for col in df.columns:
    print(
        f"{col}: "
        f"distinct={df[col].n_unique()}, "
        f"nulls={df[col].null_count()}"
    )

VendorID: distinct=2, nulls=0
lpep_pickup_datetime: distinct=47420, nulls=0
lpep_dropoff_datetime: distinct=47507, nulls=0
store_and_fwd_flag: distinct=3, nulls=1836
RatecodeID: distinct=8, nulls=1836
PULocationID: distinct=212, nulls=0
DOLocationID: distinct=241, nulls=0
passenger_count: distinct=11, nulls=1836
trip_distance: distinct=1721, nulls=0
fare_amount: distinct=1430, nulls=0
extra: distinct=20, nulls=0
mta_tax: distinct=6, nulls=0
tip_amount: distinct=1349, nulls=0
tolls_amount: distinct=22, nulls=0
ehail_fee: distinct=1, nulls=48326
improvement_surcharge: distinct=5, nulls=0
total_amount: distinct=3940, nulls=0
payment_type: distinct=6, nulls=1836
trip_type: distinct=3, nulls=1843
congestion_surcharge: distinct=5, nulls=1836
cbd_congestion_fee: distinct=3, nulls=1836

In [40]:
df.filter(
(pl.col("congestion_surcharge") != 0)
& (pl.col("congestion_surcharge") != 2.75)
& (pl.col("congestion_surcharge") != 2.5)
).select("congestion_surcharge")

shape: (1, 1)
┌──────────────────────┐
│ congestion_surcharge │
│ ---                  │
│ f64                  │
╞══════════════════════╡
│ -2.75                │
└──────────────────────┘

Upon inspecting this surcharge column we found that there is potential for negative values in the surcharge or fee columns

In [ ]:
df.filter(
    (pl.col("cbd_congestion_fee") < 0)
).select("cbd_congestion_fee")

We noticed a mismatch in the dropoff and pickup counts. Below we discovered some negative values that should not be negative.

In [90]:
df.filter(
            (pl.col("passenger_count") > 1)
        ).select(["passenger_count","lpep_dropoff_datetime", "DOLocationID"]).unique()

shape: (6_543, 3)
┌─────────────────┬───────────────────────┬──────────────┐
│ passenger_count ┆ lpep_dropoff_datetime ┆ DOLocationID │
│ ---             ┆ ---                   ┆ ---          │
│ i64             ┆ datetime[μs]          ┆ i32          │
╞═════════════════╪═══════════════════════╪══════════════╡
│ 2               ┆ 2025-01-16 18:24:33   ┆ 75           │
│ 2               ┆ 2025-01-22 17:34:19   ┆ 114          │
│ 2               ┆ 2025-01-05 13:36:38   ┆ 138          │
│ 2               ┆ 2025-01-23 08:18:29   ┆ 155          │
│ 2               ┆ 2025-01-06 22:00:35   ┆ 255          │
│ …               ┆ …                     ┆ …            │
│ 2               ┆ 2025-01-18 19:51:51   ┆ 72           │
│ 2               ┆ 2025-01-20 12:52:00   ┆ 142          │
│ 5               ┆ 2025-01-05 18:41:41   ┆ 129          │
│ 2               ┆ 2025-01-21 19:06:48   ┆ 232          │
│ 2               ┆ 2025-01-06 15:58:04   ┆ 229          │
└─────────────────┴───────────────────────┴──────────────┘

In [95]:
df2 = pl.read_parquet("s3://techcatalyst-de-2026/raw/yellow_taxi/yellow_tripdata_2025-01.parquet")
df1 = pl.read_parquet("s3://techcatalyst-de-2026/raw/green_taxi/green_tripdata_2025-01.parquet")

df2.head()

shape: (5, 20)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ total_amo ┆ congestio ┆ Airport_f ┆ cbd_conge │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ unt       ┆ n_surchar ┆ ee        ┆ stion_fee │
│ i32      ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ ge        ┆ ---       ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ f64       ┆ ---       ┆ f64       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆ f64       ┆           ┆           │
│          ┆ μs]       ┆ μs]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ 18.0      ┆ 2.5       ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:18:38  ┆ 00:26:59  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ 12.12     ┆ 2.5       ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:32:40  ┆ 00:35:13  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ 12.1      ┆ 2.5       ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:44:04  ┆ 00:46:01  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-01-0 ┆ 2025-01-0 ┆ 3         ┆ … ┆ 9.7       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:14:27  ┆ 00:20:01  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-01-0 ┆ 2025-01-0 ┆ 3         ┆ … ┆ 8.3       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:21:34  ┆ 00:25:06  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

Want to check if Green and Yellow have the same columns and schema.

In [97]:
schema1 = df1.schema
schema2 = df2.schema

for col in set(schema1) | set(schema2):
    if schema1.get(col) != schema2.get(col):
        print(
            f"{col}: "
            f"df1={schema1.get(col)} "
            f"df2={schema2.get(col)}"
        )

lpep_pickup_datetime: df1=Datetime(time_unit='us', time_zone=None) df2=None
lpep_dropoff_datetime: df1=Datetime(time_unit='us', time_zone=None) df2=None
Airport_fee: df1=None df2=Float64
tpep_pickup_datetime: df1=None df2=Datetime(time_unit='us', time_zone=None)
trip_type: df1=Int64 df2=None
tpep_dropoff_datetime: df1=None df2=Datetime(time_unit='us', time_zone=None)
ehail_fee: df1=Float64 df2=None

Here the schemas appear different. Lpep and Tpep is just a naming convetion. 
1. Green does not take passengers to the airport
2. Trip type is not a column in yellow
3. Yellow does not have ehail options.

Checking the counts of each file

In [103]:
files = [f"s3://{f}" for f in files]

for file in files:
    count = (
        pl.scan_parquet(file)
        .select(pl.len())
        .collect()
        .item()
    )
    print(file, count)

s3://techcatalyst-de-2026/raw/green_taxi/green_tripdata_2025-01.parquet 48326
s3://techcatalyst-de-2026/raw/green_taxi/green_tripdata_2025-02.parquet 46621
s3://techcatalyst-de-2026/raw/green_taxi/green_tripdata_2025-03.parquet 51539
s3://techcatalyst-de-2026/raw/green_taxi/green_tripdata_2025-04.parquet 52132
s3://techcatalyst-de-2026/raw/green_taxi/green_tripdata_2025-05.parquet 55399
s3://techcatalyst-de-2026/raw/green_taxi/green_tripdata_2026-01.parquet 40272
s3://techcatalyst-de-2026/raw/green_taxi/green_tripdata_2026-02.parquet 37373
s3://techcatalyst-de-2026/raw/green_taxi/green_tripdata_2026-03.parquet 44208
s3://techcatalyst-de-2026/raw/green_taxi/green_tripdata_2026-04.parquet 44238
s3://techcatalyst-de-2026/raw/green_taxi/green_tripdata_2026-05.parquet 44921
s3://techcatalyst-de-2026/raw/weather/weather_raw.parquet 20
s3://techcatalyst-de-2026/raw/yellow_taxi/yellow_tripdata_2025-01.parquet 3475226
s3://techcatalyst-de-2026/raw/yellow_taxi/yellow_tripdata_2025-02.parquet 3577543
s3://techcatalyst-de-2026/raw/yellow_taxi/yellow_tripdata_2025-03.parquet 4145257
s3://techcatalyst-de-2026/raw/yellow_taxi/yellow_tripdata_2025-04.parquet 3970553
s3://techcatalyst-de-2026/raw/yellow_taxi/yellow_tripdata_2025-05.parquet 4591845
s3://techcatalyst-de-2026/raw/yellow_taxi/yellow_tripdata_2026-01.parquet 3724889
s3://techcatalyst-de-2026/raw/yellow_taxi/yellow_tripdata_2026-02.parquet 3399866
s3://techcatalyst-de-2026/raw/yellow_taxi/yellow_tripdata_2026-03.parquet 3952451
s3://techcatalyst-de-2026/raw/yellow_taxi/yellow_tripdata_2026-04.parquet 3831240
s3://techcatalyst-de-2026/raw/yellow_taxi/yellow_tripdata_2026-05.parquet 4090836

In [121]:
test2 = pl.read_parquet("s3://techcatalyst-de-2026/raw/yellow_taxi/yellow_tripdata_2025-01.parquet")
test2.select(pl.col("tpep_pickup_datetime"))

shape: (3_475_226, 1)
┌──────────────────────┐
│ tpep_pickup_datetime │
│ ---                  │
│ datetime[μs]         │
╞══════════════════════╡
│ 2025-01-01 00:18:38  │
│ 2025-01-01 00:32:40  │
│ 2025-01-01 00:44:04  │
│ 2025-01-01 00:14:27  │
│ 2025-01-01 00:21:34  │
│ …                    │
│ 2025-01-31 23:01:48  │
│ 2025-01-31 23:50:29  │
│ 2025-01-31 23:26:59  │
│ 2025-01-31 23:14:34  │
│ 2025-01-31 23:56:42  │
└──────────────────────┘